In [3]:
import numpy as np

In [4]:
l = [1,2,3,4]
arr = np.array(l)
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr1 = np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [7]:
type(arr1)

numpy.ndarray

In [9]:
arr2 = np.asarray([1,2,4,5])
arr2

array([1, 2, 4, 5])

In [10]:
type(arr2)

numpy.ndarray

In [11]:
arr3 = np.asanyarray([1,2,3])
arr3

array([1, 2, 3])

In [12]:
type(arr3)

numpy.ndarray

In [13]:
arr4 = np.matrix([2,3,4,5])
arr4

matrix([[2, 3, 4, 5]])

In [14]:
type(arr4)

numpy.matrix