# Sort, Search and Counting Functions

In [31]:
import numpy as np

In [32]:
arr = np.array([4,3,6,7,6,2,8])
arr

array([4, 3, 6, 7, 6, 2, 8])

In [33]:
np.sort(arr)

array([2, 3, 4, 6, 6, 7, 8])

In [34]:
np.searchsorted(arr, 6) # 6 कहा पर जाएगा

np.int64(2)

In [35]:
arr1 = np.array([0,44,66,12,667,3,6,8,0,1,3,0])
np.count_nonzero(arr1)

9

In [36]:
np.where(arr1>6)

(array([1, 2, 3, 4, 7]),)

In [37]:
np.extract(arr1>6,arr1)

array([ 44,  66,  12, 667,   8])

In [38]:
arr1.byteswap()

array([                   0,  3170534137668829184,  4755801206503243776,
         864691128455135232, -7277254047877300224,   216172782113783808,
         432345564227567616,   576460752303423488,                    0,
          72057594037927936,   216172782113783808,                    0])

# Copies and Views:

In [39]:
arr2 = np.copy(arr1) # Deep Copy
arr1[9] = 11
arr2

array([  0,  44,  66,  12, 667,   3,   6,   8,   0,   1,   3,   0])

In [40]:
arr3 = arr1.view() # Shallow Copy
arr1[0] = 10000
arr3

array([10000,    44,    66,    12,   667,     3,     6,     8,     0,
          11,     3,     0])

# Matrix Library:

In [47]:
import numpy.matlib as nm # Min dim of matrix is 2 and it is subclass of array

In [48]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [49]:
nm.ones(10)

matrix([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Linear Algebra:

In [52]:
arr = np.array([[2,3],[4,5]])
arr1 = np.array([[1,2],[8,9]])
arr, arr1

(array([[2, 3],
        [4, 5]]),
 array([[1, 2],
        [8, 9]]))

In [53]:
np.dot(arr,arr1) # DotProduct or Matrix Multiplication

array([[26, 31],
       [44, 53]])

In [55]:
arr@arr1

array([[26, 31],
       [44, 53]])