In [3]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,4))
arr

array([[6, 6, 3, 8],
       [3, 1, 5, 4],
       [2, 1, 7, 6]])

In [5]:
arr = arr.reshape(2,-1) # Same as (2,6)
arr

array([[6, 6, 3, 8, 3, 1],
       [5, 4, 2, 1, 7, 6]])

In [6]:
arr = arr.T

In [7]:
arr.flatten() # Convert data to 1D

array([6, 5, 6, 4, 3, 2, 8, 1, 3, 7, 1, 6])

In [8]:
arr1 = np.array([1,2,3,5,7,6])
arr1

array([1, 2, 3, 5, 7, 6])

In [9]:
arr1.ndim

1

In [10]:
np.expand_dims(arr1, axis=0) # This function will expand the dimension of an array, either Zero or one, Zero a row and One mean column into 2D

array([[1, 2, 3, 5, 7, 6]])

In [11]:
arr = np.random.randint(1,101,(5,5))
arr

array([[47, 52, 28, 99, 77],
       [86, 40, 75, 85, 18],
       [48, 89, 77, 21, 40],
       [42, 67, 80, 98, 39],
       [68, 13, 30, 75, 95]])

In [12]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [13]:
np.squeeze(data)

array([1, 2, 3])

In [14]:
arr1

array([1, 2, 3, 5, 7, 6])

In [15]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 5, 5, 5, 7, 7, 7, 6, 6, 6])

In [16]:
np.roll(arr1,2)

array([7, 6, 1, 2, 3, 5])

In [17]:
np.diag(arr1)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 6]])


# Binary Operations:

In [18]:
arr2 = np.random.randint(1,10, (3,4))
arr2

array([[7, 1, 4, 6],
       [7, 7, 6, 5],
       [4, 5, 3, 7]])

In [19]:
arr3 = np.random.randint(1,10,(3,4))
arr3

array([[1, 8, 1, 5],
       [9, 1, 5, 5],
       [3, 1, 1, 9]])

In [20]:
arr2+arr3

array([[ 8,  9,  5, 11],
       [16,  8, 11, 10],
       [ 7,  6,  4, 16]])

In [21]:
arr2*arr3

array([[ 7,  8,  4, 30],
       [63,  7, 30, 25],
       [12,  5,  3, 63]])

In [22]:
arr2/arr3

array([[7.        , 0.125     , 4.        , 1.2       ],
       [0.77777778, 7.        , 1.2       , 1.        ],
       [1.33333333, 5.        , 3.        , 0.77777778]])

In [23]:
arr2%arr3

array([[0, 1, 0, 1],
       [7, 0, 1, 0],
       [1, 0, 0, 7]])

In [24]:
arr2**arr3

array([[       7,        1,        4,     7776],
       [40353607,        7,     7776,     3125],
       [      64,        5,        3, 40353607]])

In [25]:
arr2&arr3

array([[1, 0, 0, 4],
       [1, 1, 4, 5],
       [0, 1, 1, 1]])

In [26]:
~arr2

array([[-8, -2, -5, -7],
       [-8, -8, -7, -6],
       [-5, -6, -4, -8]])

In [27]:
arr2|arr3

array([[ 7,  9,  5,  7],
       [15,  7,  7,  5],
       [ 7,  5,  3, 15]])

# String Function:

In [28]:
arr4 = np.array(['Anurag', 'Pareek'])
arr4

array(['Anurag', 'Pareek'], dtype='<U6')

In [29]:
np.char.upper(arr4)

array(['ANURAG', 'PAREEK'], dtype='<U6')

In [30]:
np.char.lower(arr4)

array(['anurag', 'pareek'], dtype='<U6')

In [31]:
np.char.title(arr4)

array(['Anurag', 'Pareek'], dtype='<U6')

In [32]:
np.char.capitalize(arr4)

array(['Anurag', 'Pareek'], dtype='<U6')

# Numerical/Mathematical Fucntions

In [33]:
arr1 = np.random.randint(1,11,(4,5))
arr2 = np.random.randint(1,11,(4,5))
arr1, arr2

(array([[3, 7, 2, 5, 7],
        [8, 4, 9, 2, 3],
        [2, 5, 8, 6, 7],
        [5, 8, 8, 4, 4]]),
 array([[ 1,  6,  2,  8,  2],
        [ 7,  4,  6,  4,  3],
        [ 1,  1,  3,  6,  9],
        [ 7,  3,  2,  1, 10]]))

In [34]:
np.sin(arr1)

array([[ 0.14112001,  0.6569866 ,  0.90929743, -0.95892427,  0.6569866 ],
       [ 0.98935825, -0.7568025 ,  0.41211849,  0.90929743,  0.14112001],
       [ 0.90929743, -0.95892427,  0.98935825, -0.2794155 ,  0.6569866 ],
       [-0.95892427,  0.98935825,  0.98935825, -0.7568025 , -0.7568025 ]])

In [35]:
np.cos(arr1)

array([[-0.9899925 ,  0.75390225, -0.41614684,  0.28366219,  0.75390225],
       [-0.14550003, -0.65364362, -0.91113026, -0.41614684, -0.9899925 ],
       [-0.41614684,  0.28366219, -0.14550003,  0.96017029,  0.75390225],
       [ 0.28366219, -0.14550003, -0.14550003, -0.65364362, -0.65364362]])

In [36]:
np.tan(arr1)

array([[-0.14254654,  0.87144798, -2.18503986, -3.38051501,  0.87144798],
       [-6.79971146,  1.15782128, -0.45231566, -2.18503986, -0.14254654],
       [-2.18503986, -3.38051501, -6.79971146, -0.29100619,  0.87144798],
       [-3.38051501, -6.79971146, -6.79971146,  1.15782128,  1.15782128]])

In [37]:
np.tanh(arr1)

array([[0.99505475, 0.99999834, 0.96402758, 0.9999092 , 0.99999834],
       [0.99999977, 0.9993293 , 0.99999997, 0.96402758, 0.99505475],
       [0.96402758, 0.9999092 , 0.99999977, 0.99998771, 0.99999834],
       [0.9999092 , 0.99999977, 0.99999977, 0.9993293 , 0.9993293 ]])

In [38]:
np.log2(arr1)

array([[1.5849625 , 2.80735492, 1.        , 2.32192809, 2.80735492],
       [3.        , 2.        , 3.169925  , 1.        , 1.5849625 ],
       [1.        , 2.32192809, 3.        , 2.5849625 , 2.80735492],
       [2.32192809, 3.        , 3.        , 2.        , 2.        ]])

In [39]:
np.exp(arr1)

array([[2.00855369e+01, 1.09663316e+03, 7.38905610e+00, 1.48413159e+02,
        1.09663316e+03],
       [2.98095799e+03, 5.45981500e+01, 8.10308393e+03, 7.38905610e+00,
        2.00855369e+01],
       [7.38905610e+00, 1.48413159e+02, 2.98095799e+03, 4.03428793e+02,
        1.09663316e+03],
       [1.48413159e+02, 2.98095799e+03, 2.98095799e+03, 5.45981500e+01,
        5.45981500e+01]])

In [41]:
np.sqrt(arr1)

array([[1.73205081, 2.64575131, 1.41421356, 2.23606798, 2.64575131],
       [2.82842712, 2.        , 3.        , 1.41421356, 1.73205081],
       [1.41421356, 2.23606798, 2.82842712, 2.44948974, 2.64575131],
       [2.23606798, 2.82842712, 2.82842712, 2.        , 2.        ]])

In [44]:
np.pow(arr1,10)

array([[     59049,  282475249,       1024,    9765625,  282475249],
       [1073741824,    1048576, 3486784401,       1024,      59049],
       [      1024,    9765625, 1073741824,   60466176,  282475249],
       [   9765625, 1073741824, 1073741824,    1048576,    1048576]])

In [45]:
np.mean(arr1)

np.float64(5.35)

In [46]:
np.median(arr1)

np.float64(5.0)

In [48]:
np.std(arr1)

np.float64(2.2422087324778666)

In [49]:
np.var(arr1)

np.float64(5.027500000000002)

In [50]:
np.min(arr1)

np.int64(2)

In [52]:
np.max(arr1)

np.int64(9)