In [150]:
from random import random

import numpy as np
import pandas as pd

In [151]:
l = [1,2,3,4]
arr = np.array(l) # It is by default 1D
arr

array([1, 2, 3, 4])

In [152]:
type(arr)

numpy.ndarray

In [153]:
arr1 = np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [154]:
type(arr1)

numpy.ndarray

In [155]:
arr2 = np.asarray([1,2,4,5])
arr2

array([1, 2, 4, 5])

In [156]:
type(arr2)

numpy.ndarray

In [157]:
arr3 = np.asanyarray([1,2,3])
arr3

array([1, 2, 3])

In [158]:
type(arr3)

numpy.ndarray

In [159]:
arr4 = np.matrix([2,3,4,5]) # It is by default 2D, it is subclass of array
arr4

matrix([[2, 3, 4, 5]])

In [160]:
type(arr4)

numpy.matrix

In [161]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [162]:
m1 = np.matrix([1,2,3])
m1

matrix([[1, 2, 3]])

In [163]:
l1 = [1,2,3]
l1

[1, 2, 3]

In [164]:
np.asanyarray(a1) # Not convert the input when it's already a subclass

array([1, 2, 3])

In [165]:
np.asanyarray(m1) # Not convert the input when it's already a subclass

matrix([[1, 2, 3]])

In [166]:
np.asanyarray(l1) # Not convert the input when it's already a subclass

array([1, 2, 3])

In [167]:
np.asarray(a1) # Not convert the input when it's already an array

array([1, 2, 3])

In [168]:
np.asarray(a1) # Not convert the input when it's already an array

array([1, 2, 3])

In [169]:
np.asarray(l1) # Not convert the input when it's already an array

array([1, 2, 3])

In [170]:
np.array(a1) # Will convert into array

array([1, 2, 3])

In [171]:
type(np.array(m1)) # Will convert into array

numpy.ndarray

In [172]:
np.array(l1) # Will convert into array

array([1, 2, 3])

In [173]:
# Shallow copy
a = [1,2,4]
b = a
a[0] = 2
b

[2, 2, 4]

In [174]:
# Deep copy
a = [1,2,3]
b = np.copy(a)
a[0] = 2
b

array([1, 2, 3])

In [175]:
# X and Y are rows and column resp.
np.fromfunction(lambda x, y: x==y, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [176]:
np.fromfunction(lambda x, y: x*y, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [177]:
iterable = (i*i for i in range(5))
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [178]:
np.fromstring('1 2 3 4 5',sep=" ", dtype=int)

array([1, 2, 3, 4, 5])

In [179]:
a2 = np.array([2,3,4,5,6])
a3 = np.array([[2,3,4,5,6],[1,2,3,9,8]])

In [180]:
a2

array([2, 3, 4, 5, 6])

In [181]:
a3

array([[2, 3, 4, 5, 6],
       [1, 2, 3, 9, 8]])

In [182]:
a2.ndim

1

In [183]:
a3.ndim

2

In [184]:
a2.size

5

In [185]:
a3.size

10

In [186]:
a2.shape

(5,)

In [187]:
a3.shape

(2, 5)

In [188]:
a2.dtype

dtype('int64')

In [189]:
a3.dtype

dtype('int64')

In [190]:
a4 = np.array((1.0,4,6,9,3,7))
a4

array([1., 4., 6., 9., 3., 7.])

In [191]:
a4.dtype

dtype('float64')

In [192]:
list(np.arange(2.3,5.6,0.3)) # Works with float not like range()
# Array to List convertion is also possible

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [193]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [194]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [195]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [196]:
np.zeros((4,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [197]:
np.zeros((4,2,4)).ndim

3

In [198]:
np.zeros((4,5,2,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0

In [199]:
np.ones(4)

array([1., 1., 1., 1.])

In [200]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [201]:
one = np.ones((2,2,3))

In [202]:
one*4

array([[[4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.]]])

In [203]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [204]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [205]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [209]:
r_data = np.random.randn(3,5)

In [208]:
pd.DataFrame(r_data)

0         1         2         3         4
0 -0.414116  0.281976  1.058045 -0.700058  1.318164
1 -0.783664  0.679869  0.037467  0.443336 -1.013919
2 -0.360669 -1.851163  0.602094  0.897499 -0.299663

In [210]:
np.random.rand(3,4)

array([[0.41168151, 0.80678159, 0.14938813, 0.21926645],
       [0.52144028, 0.58451966, 0.30606849, 0.45596022],
       [0.23888151, 0.81516932, 0.33459219, 0.24352078]])

In [211]:
np.random.randint(1,110,(5,6))

array([[ 18, 106,  94,  64,  72,  39],
       [ 42,  68,  51,  70,  94, 100],
       [ 84,   5,  64,  33,  62,  88],
       [  3,  73,  93,  75,  50,  79],
       [ 87,  54,  74,  89,  31,  89]])

In [225]:
array = np.random.rand(3,4)
array

array([[0.26394004, 0.04081646, 0.48512908, 0.57004357],
       [0.62839007, 0.41232719, 0.04699762, 0.61569554],
       [0.39255867, 0.71346508, 0.36086179, 0.18419005]])

In [228]:
array = array.reshape(6,2) # When to use -1 ??
array

array([[0.26394004, 0.04081646],
       [0.48512908, 0.57004357],
       [0.62839007, 0.41232719],
       [0.04699762, 0.61569554],
       [0.39255867, 0.71346508],
       [0.36086179, 0.18419005]])

In [229]:
array[1][1]

np.float64(0.5700435686471264)

In [233]:
array[3][1]

np.float64(0.6156955395339204)

In [234]:
array[2:5,0]

array([0.62839007, 0.04699762, 0.39255867])

In [240]:
arr5 = np.random.randint(1,101,(5,7))
arr5

array([[68, 82,  3,  7, 38, 99, 21],
       [56, 45, 47, 45, 21, 59, 39],
       [78, 54, 18, 88,  3, 39, 75],
       [19, 29, 92, 89, 66, 40, 93],
       [ 1, 52, 88, 69, 68, 40, 96]])

In [239]:
arr5[arr5>50]

array([52, 98, 62, 92, 84, 81, 69, 97, 99, 90, 94, 94, 67, 56, 80, 53, 93,
       94])

In [242]:
arr5[2:4,[1,2]]

array([[54, 18],
       [29, 92]])

In [244]:
arr5[0][0] = 5000
arr5

array([[5000,   82,    3,    7,   38,   99,   21],
       [  56,   45,   47,   45,   21,   59,   39],
       [  78,   54,   18,   88,    3,   39,   75],
       [  19,   29,   92,   89,   66,   40,   93],
       [   1,   52,   88,   69,   68,   40,   96]])

In [246]:
a2 = np.random.randint(1,3,(3,3))
a3 = np.random.randint(4,6,(3,3))
a2 ,a3

(array([[1, 1, 2],
        [1, 2, 2],
        [2, 2, 2]]),
 array([[4, 4, 5],
        [5, 4, 5],
        [5, 5, 5]]))

In [247]:
a2 + a3

array([[5, 5, 7],
       [6, 6, 7],
       [7, 7, 7]])

In [248]:
a2/a3

array([[0.25, 0.25, 0.4 ],
       [0.2 , 0.5 , 0.4 ],
       [0.4 , 0.4 , 0.4 ]])

In [249]:
a2-a3

array([[-3, -3, -3],
       [-4, -2, -3],
       [-3, -3, -3]])

In [250]:
a2*a3

array([[ 4,  4, 10],
       [ 5,  8, 10],
       [10, 10, 10]])

In [251]:
# For matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix.
a2@a3

array([[19, 18, 20],
       [24, 22, 25],
       [28, 26, 30]])

In [254]:
a2/0

/var/folders/n7/4jl4_vxn1fx98qz38bwr30kc0000gn/T/ipykernel_52121/42991845.py:1: RuntimeWarning: divide by zero encountered in divide
  a2/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [255]:
a2**3

array([[1, 1, 8],
       [1, 8, 8],
       [8, 8, 8]])

# Broadcasting:

In [264]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [265]:
row = np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [266]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [269]:
col = np.array([[1,2,3,4]]).T
col

array([[1],
       [2],
       [3],
       [4]])

In [270]:
arr+col

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [272]:
arr = np.random.randint(1,101,(5,6))
arr

array([[77, 71, 99, 49, 60, 41],
       [27, 34, 88, 90, 77, 33],
       [36, 75, 45, 19, 24, 45],
       [87, 31, 24, 65, 75, 65],
       [ 1, 72, 23, 68, 77,  8]])

In [273]:
np.sqrt(arr)

array([[8.77496439, 8.42614977, 9.94987437, 7.        , 7.74596669,
        6.40312424],
       [5.19615242, 5.83095189, 9.38083152, 9.48683298, 8.77496439,
        5.74456265],
       [6.        , 8.66025404, 6.70820393, 4.35889894, 4.89897949,
        6.70820393],
       [9.32737905, 5.56776436, 4.89897949, 8.06225775, 8.66025404,
        8.06225775],
       [1.        , 8.48528137, 4.79583152, 8.24621125, 8.77496439,
        2.82842712]])

In [274]:
np.exp(arr)

array([[2.75851345e+33, 6.83767123e+30, 9.88903032e+42, 1.90734657e+21,
        1.14200739e+26, 6.39843494e+17],
       [5.32048241e+11, 5.83461743e+14, 1.65163625e+38, 1.22040329e+39,
        2.75851345e+33, 2.14643580e+14],
       [4.31123155e+15, 3.73324200e+32, 3.49342711e+19, 1.78482301e+08,
        2.64891221e+10, 3.49342711e+19],
       [6.07603023e+37, 2.90488497e+13, 2.64891221e+10, 1.69488924e+28,
        3.73324200e+32, 1.69488924e+28],
       [2.71828183e+00, 1.85867175e+31, 9.74480345e+09, 3.40427605e+29,
        2.75851345e+33, 2.98095799e+03]])

In [276]:
np.log10(arr)

array([[1.88649073, 1.85125835, 1.99563519, 1.69019608, 1.77815125,
        1.61278386],
       [1.43136376, 1.53147892, 1.94448267, 1.95424251, 1.88649073,
        1.51851394],
       [1.5563025 , 1.87506126, 1.65321251, 1.2787536 , 1.38021124,
        1.65321251],
       [1.93951925, 1.49136169, 1.38021124, 1.81291336, 1.87506126,
        1.81291336],
       [0.        , 1.8573325 , 1.36172784, 1.83250891, 1.88649073,
        0.90308999]])